### ISSUE TITLE
Sent messages should be saved in a DB for querying

### ISSUE THREAD

**Issue by rlisagor** [rlisagor/ahv-council-thing#2]
What kind of querying?

**Comment by rgwood** [comment]
Some random queries I can see myself doing:
- How many letters have been sent (either for a particular project or for all time)?
- Who sends the most letters (across multiple projects, for identifying prospective volunteers/speakers)?

It would be nice if I could query the results in SQL but it's not 100% necessary. Since I'm probably too cheap to pay for a relational DB instance, maybe a cheap NoSQL DB like AWS DynamoDB or Azure Table Storage? Open to other ideas too.
